# Generated by Django 4.2.6 on 2023-10-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COUNTRY',
            fields=[
                ('ID_COUNTRY', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME_COUNTRY', models.CharField(max_length=64, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='ISG',
            fields=[
                ('ID_ISG', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME_ISG', models.CharField(max_length=512, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='GOODS',
            fields=[
                ('ID_TOVAR', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME_TOVAR', models.CharField(max_length=512, verbose_name='Название товара')),
                ('BARCOD', models.CharField(max_length=256, verbose_name='Штрихкод')),
                ('ID_COUNTRY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_goods', to='app.country', verbose_name='Страна производитель')),
                ('ID_ISG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_goods', to='app.isg', verbose_name='Производитель товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
